### ISSUE TITLE
Running mod on server causes strings not to be translated properly within the console

### ISSUE THREAD

**Issue by Cpt-Dingus** [LieOnLion/More-Crafting-Tables#4]
Tested with Fabric server 1.21 versions 1.0.1 and 1.0.0, Quad 1.2.7 and 1.3.0, always happens. Mod list: 
```
        - fabric-api 0.102.0+1.21
                <fabric api nonsense>...
        - lolmct 1.2.8
        - minecraft 1.21
        - quad 1.3.0-beta.5
```

Output in console:  https://cpy.pt/AcH6N5KV

**Comment by lieonlion** [comment]
unfortunately this is a bug with (I believe) Minecraft itself, and I cant fix it

**Comment by Cpt-Dingus** [comment]
This only happens when MCT is loaded in the mod folder.

**Comment by lieonlion** [comment]
Yes, i am aware of the issue, still, its an issue with how minecraft handles mixing lang files on the server
